"""NSE liquid stock universe — Nifty 500 constituents.

Used by trade_decision to gate positions to tradeable, liquid names.
Microcaps outside this set are skipped: ₹50k position sizes can materially
move thin stocks, and exit slippage becomes unpredictable in live trading.

MAINTENANCE: refresh quarterly against NSE's published index page:
  https://www.nseindia.com/products-services/indices-nifty500-index
or run:
  python scripts/refresh_nifty500.py
to auto-pull and regenerate this file.

Last updated: 2026-05-28 (Nifty 500 constituents)
"""

# fmt: off
NIFTY_500: frozenset[str] = frozenset({
    # ── Nifty 50 ──────────────────────────────────────────────────────────
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
    "BAJAJ-AUTO", "BAJAJFINSV", "BAJFINANCE", "BHARTIARTL", "BPCL",
    "BRITANNIA", "CIPLA", "COALINDIA", "DIVISLAB", "DRREDDY",
    "EICHERMOT", "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE",
    "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", "INDUSINDBK",
    "INFY", "ITC", "JSWSTEEL", "KOTAKBANK", "LT",
    "LTIM", "M&M", "MARUTI", "NESTLEIND", "NTPC",
    "ONGC", "POWERGRID", "RELIANCE", "SBILIFE", "SBIN",
    "SHRIRAMFIN", "SUNPHARMA", "TATACONSUM", "TATAMOTORS", "TATASTEEL",
    "TCS", "TECHM", "TITAN", "ULTRACEMCO", "WIPRO",

    # ── Nifty Next 50 ─────────────────────────────────────────────────────
    "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "AUROPHARMA", "BANKBARODA",
    "BERGEPAINT", "BOSCHLTD", "CANBK", "CHOLAFIN", "CONCOR",
    "COROMANDEL", "CUMMINSIND", "DABUR", "DMART", "FEDERALBNK",
    "GAIL", "GODREJCP", "GODREJPROP", "HAVELLS", "ICICIPRULI",
    "ICICIGI", "INDUSTOWER", "IRCTC", "JINDALSTEL", "LODHA",
    "LUPIN", "MARICO", "MCDOWELL-N", "MPHASIS", "MUTHOOTFIN",
    "NAUKRI", "OBEROIRLTY", "OFSS", "PAGEIND", "PETRONET",
    "PFC", "PIIND", "RECLTD", "SAIL", "SIEMENS",
    "SUNTV", "TORNTPHARM", "TRENT", "TVSMOTOR", "UBL",
    "UNIONBANK", "VBL", "VEDL", "VOLTAS", "ZYDUSLIFE",

    # ── Nifty Midcap 150 ──────────────────────────────────────────────────
    "ABCAPITAL", "ABFRL", "ABIRLANUVO", "ACC", "APLAPOLLO",
    "ASTRAL", "ATUL", "AUBANK", "BALKRISIND", "BANDHANBNK",
    "BATAINDIA", "BEL", "BHEL", "BIOCON", "BLUESTARCO",
    "BRIGADE", "BSE", "CAMS", "CANFINHOME", "CARBORUNIV",
    "CASTROLIND", "CDSL", "CENTRALBNK", "CHAMBLFERT", "CHENNPETRO",
    "CESC", "CGPOWER", "COLPAL", "CROMPTON", "CSBBANK",
    "DALBHARAT", "DATAPATTNS", "DEEPAKNTR", "DELTACORP", "DELHIVERY",
    "DIXON", "EMAMILTD", "ENGINERSIN", "ESCORTS", "EXIDEIND",
    "FACT", "FINCABLES", "FORTIS", "GLENMARK", "GMRAIRPORT",
    "GNFC", "GODREJIND", "GPPL", "GUJGASLTD", "HAL",
    "HFCL", "HUDCO", "IDFCFIRSTB", "IIFL", "INDHOTEL",
    "INDIANB", "INDIGO", "INOXWIND", "IOB", "IPCALAB",
    "IRB", "IRCON", "JKCEMENT", "JSWENERGY", "JUBILANT",
    "JUBLFOOD", "KAJARIACER", "KALPATPOWR", "KANSAINER", "KPITTECH",
    "LALPATHLAB", "LAURUSLABS", "LICHSGFIN", "LTTS", "MAHABANK",
    "MANAPPURAM", "MAXHEALTH", "MCX", "METROPOLIS", "MGL",
    "MINDTREE", "MOTILALOFS", "MRPL", "MTAR", "NATIONALUM",
    "NBCC", "NCC", "NHPC", "NIACL", "NLCINDIA",
    "NMDC", "NSLNISP", "NTPCGREEN", "OIL", "OLECTRA",
    "PGHH", "PHOENIXLTD", "PNB", "POLYCAB", "PRESTIGE",
    "PRICOL", "PRINCEPIPE", "PVRINOX", "RAYMOND", "REDINGTON",
    "RELAXO", "RITES", "SAFARI", "SAPPHIRE", "SCHAEFFLER",
    "SHYAMMETL", "SJVN", "SKFINDIA", "SOBHA", "SONACOMS",
    "STARHEALTH", "SUNTECK", "SUPREMEIND", "SUVENPHAR", "SUZLON",
    "SWSOLAR", "SYMPHONY", "TANLA", "TATACHEM", "TATACOMM",
    "TATAELXSI", "TATAPOWER", "TATVA", "TEAMLEASE", "THERMAX",
    "TIINDIA", "TIMKEN", "TORNTPOWER", "TTKPRESTIG", "TVSHLTD",
    "UCOBANK", "UJJIVAN", "USHA", "UTIAMC", "VAIBHAVGBL",
    "VEDANT", "VGUARD", "VINATIORGA", "WELCORP", "WHIRLPOOL",
    "WOCKPHARMA", "YESBANK", "ZENSARTECH", "ZOMATO", "ZYDUSWELL",

    # ── Nifty Smallcap 250 (selective — top ~150 by liquidity) ────────────
    "AARTIIND", "AAVAS", "ABBOTINDIA", "ABSLBANETF", "ACE",
    "ACRYSIL", "AEGISCHEM", "AFFLE", "AGARIND", "AGI",
    "AGROPHOS", "AIIL", "AIAENG", "AJANTPHARM", "ALKEM",
    "ALKYLAMINE", "ALLCARGO", "ALLSEC", "ALOKINDS", "AMBER",
    "AMJLAND", "AMRUTANJAN", "ANGELONE", "ANURAS", "APARINDS",
    "APOLLO", "APOLLOPIPE", "APTUS", "ARMAN", "ARVIND",
    "ASALCBR", "ASHIANA", "ASHOKLEY", "ASKAUTOLTD", "ASTERDM",
    "ATGL", "ATLASCYCLE", "ATUL", "AVANTIFEED", "AYMSYNTEX",
    "BAJAJHCARE", "BALAMINES", "BALMLAWRIE", "BANSALWIRE", "BAOSB",
    "BASF", "BAYERCROP", "BEML", "BFINVEST", "BIRLACABLE",
    "BIRLAMONEY", "BLUEDART", "BORORENEW", "BOROLTD", "BPCLINDIA",
    "CAPLIPOINT", "CARERATING", "CASTEXTECH", "CEATLTD", "CENTURY",
    "CENTURYPLY", "CERA", "CLEAN", "CMSINFO", "COFORGE",
    "CONFIPET", "CONTROLPR", "CRAFTSMAN", "CRISIL", "CYIENT",
    "DCMSHRIRAM", "DCXINDIA", "DEEPAKFERT", "DFMFOODS", "DHANUKA",
    "DHANI", "DOLLAR", "DREDGECORP", "EDELWEISS", "ELGIEQUIP",
    "EPL", "EQUITASBNK", "ETHOSLTD", "FINEORG", "FINPIPE",
    "FINOLEX", "FLUOROCHEM", "FOODWORKS", "FSL", "GAEL",
    "GARFIBRES", "GEPIL", "GESHIP", "GHCL", "GILLETTE",
    "GLAXO", "GLOBE", "GMDCLTD", "GODFRYPHLP", "GPPL",
    "GRANULES", "GRAPHITE", "GREENPANEL", "GRINDWELL", "GSFC",
    "GSPL", "GUJALKALI", "GUJGAS", "HAPPSTMNDS", "HARDWYN",
    "HERITGFOOD", "HEXAWARE", "HIKAL", "HILTON", "HINDCOPPER",
    "HINDPETRO", "HONASA", "IBREALEST", "IDEAFORGE", "IDFCFIRSTB",
    "IGPL", "IIFLSEC", "IMAGICAA", "IMFA", "INDIAGLYCO",
    "INDIANHUME", "INDRAMEDCO", "INFIBEAM", "INFOBEAN", "INGERRAND",
    "INTELLECT", "INOXGREEN", "ISGEC", "ITDCEM", "IVRCL",
    "J&KBANK", "JAGRAN", "JAMNAAUTO", "JAYAGROGN", "JAYKAYENT",
    "JBCHEPHARM", "JCHAC", "JETAIRWAYS", "JKIL", "JKLAKSHMI",
    "JKPAPER", "JKTYRE", "JPPOWER", "JSWHL", "JTEKTINDIA",
    "KALYAN", "KANCHI", "KARDA", "KARURVYSYA", "KDDL",
    "KFINTECH", "KIRLOSENG", "KMSUGAR", "KNRCON", "KOLTEPATIL",
    "KOPRAN", "KOTAKPSU", "KPIL", "KRBL", "KSCL",
    "KTKBANK", "LATENTVIEW", "LEMONTREE", "LGBBROSLTD", "LLOYDSENGG",
    "LNTFH", "LUXIND", "MAHLOG", "MANINFRA", "MAPMYINDIA",
    "MASTEK", "MAYURUNIQ", "MEDICAMEQ", "MEDPLUS", "MEGASOFT",
    "MELSTAR", "MINDACORP", "MIRZAINT", "MKPL", "MMTC",
    "MOIL", "MOLDTKPAC", "MOREPENLAB", "MSTCLTD", "MUTHOOTMF",
    "NARAYANA", "NATCOPHARM", "NAVINFLUOR", "NESCO", "NETWORK18",
    "NIFTYQLVT", "NIITLTD", "NILKAMAL", "NOCIL", "NRBBEARING",
    "NUVAMA", "NUVOCO", "OLECTRA", "OMAXE", "ONEPOINT",
    "ORCHPHARMA", "ORIENTELEC", "ORIENTPPR", "PATELENG", "PATANJALI",
    "PCJEWELLER", "PDSL", "PENIND", "PERSISTENT", "PFIZER",
    "PGHL", "PNB", "POLICYBZR", "POLYMED", "PRAKASH",
    "PRECWIRE", "PRIVISCL", "PRUDENT", "PTCIL", "PURVA",
    "RADICO", "RAJESHEXPO", "RALLIS", "RAMCOCEM", "RAMCOSYS",
    "RATNAMANI", "RBLBANK", "RHIM", "RICOAUTO", "RKFORGE",
    "ROSSARI", "ROUTE", "RPGLIFE", "RPOWER", "RTNL",
    "RUSHIL", "SADBHAV", "SAGAR", "SANOFI", "SAPPHIRE",
    "SARDAEN", "SAVITA", "SBICARD", "SEQUENT", "SHARDACROP",
    "SHARDAMOTR", "SHILPAMED", "SHOPERSTOP", "SHREDIGCEM", "SHYAMMETL",
    "SKIPPER", "SMLISUZU", "SOLARA", "SOUTHBANK", "SPANDANA",
    "SPARC", "SPICEJET", "SPTL", "STAR", "STYLAMIND",
    "SUDARSCHEM", "SUMICHEM", "SUMIT", "SUNDARMFIN", "SUNDRMFAST",
    "SUNFLAG", "SUNTECK", "SUPRAJIT", "SUPRIYA", "SURYAROSNI",
    "SUVEN", "SWELECTES", "SYNGENE", "TARSONS", "TATAINVEST",
    "TCNSBRANDS", "TDPOWERSYS", "TECHNOCRAFT", "TEJASNET", "TEXRAIL",
    "THYROCARE", "TIDEWATER", "TIMESGTY", "TIPS", "TIPLSLTD",
    "TMVL", "TNPL", "TORENTPOWER", "TREEHOUSE", "TRIDENT",
    "TRIGYN", "TRIVENI", "TRITURBINE", "TTML", "TVTODAY",
    "UGARSUGAR", "UNIPARTS", "UNITDSPR", "UNIVCABLES", "UPCL",
    "UTIAMC", "UTTAMSTL", "V2RETAIL", "VAIBHAVGBL", "VARDHMAN",
    "VARROC", "VGUARD", "VIPIND", "VMART", "VRAJINDIA",
    "VSTIND", "VSTLTD", "WABAG", "WATERBASE", "WELSPUNIND",
    "WESTLIFE", "WINDMACHINES", "WONDERLA", "XCHANGING", "XPRO",
    "ZENITHEXPO", "ZENTEC", "ZFCVINDIA", "ZODIACLOTH", "ZUARI",
})
# fmt: on


def is_liquid(symbol: str) -> bool:
    """Return True if symbol is in the Nifty 500 liquid universe."""
    return symbol.upper() in NIFTY_500
